# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_builder_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(742, 499)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.source = QtWidgets.QTreeView(Dialog)
        self.source.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source.sizePolicy().hasHeightForWidth())
        self.source.setSizePolicy(sizePolicy)
        self.source.setAutoFillBackground(True)
        self.source.setObjectName("source")
        self.source.header().setVisible(True)
        self.horizontalLayout.addWidget(self.source)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.button_add_menu = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_menu.sizePolicy().hasHeightForWidth())
        self.button_add_menu.setSizePolicy(sizePolicy)
        self.button_add_menu.setObjectName("button_add_menu")
        self.gridLayout.addWidget(self.button_add_menu, 9, 0, 1, 1)
        self.label_database = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_database.sizePolicy().hasHeightForWidth())
        self.label_database.setSizePolicy(sizePolicy)
        self.label_database.setObjectName("label_database")
        self.gridLayout.addWidget(self.label_database, 1, 0, 1, 1)
        self.combo_database = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_database.sizePolicy().hasHeightForWidth())
        self.combo_database.setSizePolicy(sizePolicy)
        self.combo_database.setEditable(False)
        self.combo_database.setObjectName("combo_database")
        self.gridLayout.addWidget(self.combo_database, 2, 0, 1, 1)
        self.combo_profile = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_profile.sizePolicy().hasHeightForWidth())
        self.combo_profile.setSizePolicy(sizePolicy)
        self.combo_profile.setEditable(True)
        self.combo_profile.setObjectName("combo_profile")
        self.gridLayout.addWidget(self.combo_profile, 7, 0, 1, 1)
        self.label_profile = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_profile.sizePolicy().hasHeightForWidth())
        self.label_profile.setSizePolicy(sizePolicy)
        self.label_profile.setObjectName("label_profile")
        self.gridLayout.addWidget(self.label_profile, 5, 0, 1, 1)
        self.button_delete_profile = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_delete_profile.sizePolicy().hasHeightForWidth())
        self.button_delete_profile.setSizePolicy(sizePolicy)
        self.button_delete_profile.setText("")
        self.button_delete_profile.setObjectName("button_delete_profile")
        self.gridLayout.addWidget(self.button_delete_profile, 7, 1, 1, 1)
        self.combo_schema = QtWidgets.QComboBox(Dialog)
        self.combo_schema.setObjectName("combo_schema")
        self.gridLayout.addWidget(self.combo_schema, 4, 0, 1, 1)
        self.label_schema = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_schema.sizePolicy().hasHeightForWidth())
        self.label_schema.setSizePolicy(sizePolicy)
        self.label_schema.setObjectName("label_schema")
        self.gridLayout.addWidget(self.label_schema, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.activate_menubar = QtWidgets.QCheckBox(Dialog)
        self.activate_menubar.setObjectName("activate_menubar")
        self.horizontalLayout_2.addWidget(self.activate_menubar)
        self.activate_dock = QtWidgets.QCheckBox(Dialog)
        self.activate_dock.setObjectName("activate_dock")
        self.horizontalLayout_2.addWidget(self.activate_dock)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Menu Configuration"))
        self.button_add_menu.setText(_translate("Dialog", "Add a menu"))
        self.label_database.setText(_translate("Dialog", "Choose database where profiles are stored"))
        self.label_profile.setText(_translate("Dialog", "Choose profile"))
        self.button_delete_profile.setToolTip(_translate("Dialog", "Delete current profile"))
        self.label_schema.setText(_translate("Dialog", "Choose schema"))
        self.label.setText(_translate("Dialog", "Activate profile"))
        self.activate_menubar.setText(_translate("Dialog", "Main menu bar"))
        self.activate_dock.setText(_translate("Dialog", "dock"))

